### ISSUE TITLE
Add React Day Berlin discount

### ISSUE THREAD

**Issue by frnzmlc** [reactvienna/partner-events#1]
[React Day Berlin](https://reactday.berlin)
December 2, 2017
10% discount available with code REACTVIENNA
https://www.eventbrite.com/e/react-day-berlin-2017-tickets-37159994544?discount=ReactVienna

**Comment by nikgraf** [comment]
@frnzmlc can you please add a PR to the readme?

**Comment by nikgraf** [comment]
Closing the issue since the event is over …
